export enum PhotoType {
    PROFILE_DISTRIBUTOR = 'PROFILE_DISTRIBUTOR',
    PROFILE_REPRESENTATIVE  ='PROFILE_REPRESENTATIVE',
    PROFILE_CUSTOMER ='PROFILE_CUSTOMER',
    PROFILE_APP_CUSTOMER = 'PROFILE_APP_CUSTOMER',
    REPRESENTATIVE = 'REPRESENTATIVE',
    MANUFACTURER = 'MANUFACTURER',
    PRODUCT = 'PRODUCT',
    FEDERAL_TAX_ID = 'FEDERAL_TAX_ID',
    SIGNATURE_CUSTOMER = 'SIGNATURE_CUSTOMER',
    PHOTOGROUP = 'PHOTOGROUP',
    ORDER_SIGNATURE = 'ORDER_SIGNATURE',
    BRAND_LOGO_DISTRIBUTOR = 'BRAND_LOGO_DISTRIBUTOR',
}

export enum ImageModelStatus {
    IMAGE_READY_TO_COPY = 'IMAGE_READY_TO_COPY',
    IMAGE_COPYING_ERROR = 'IMAGE_COPYING_ERROR',
    IMAGE_COPIED = 'IMAGE_COPIED',
    IMAGE_PROCESS_STARTED = 'IMAGE_PROCESS_STARTED',
    IMAGE_PROCESS_ERROR = 'IMAGE_PROCESS_ERROR',
    IMAGE_PROCESS_DONE = 'IMAGE_PROCESS_DONE',
}
